module.exports = {
    FETCH_SETTINGS: 'fetch-settings-from-store',
    SAVE_SETTINGS: 'save-settings-to-store',
    HANDLE_FETCH_SETTINGS: 'handle-fetch-settings-from-store',
    BACKUP_TO_DRIVE: 'backup-to-drive',
    HANDLE_BACKUP_TO_DRIVE: 'handle-backup-to-drive',
    HANDLE_BACKUP_PROGRESS: 'handle-backup-progress',
    DELETE_FILE: 'delete-file-from-drive',
    FETCH_FILES_ON_DRIVE: 'fetch-files-on-drive',
    HANDLE_FETCH_FILES_ON_DRIVE: 'handle-fetch-files-on-drive',
    FETCH_STORAGE_QUOTA: 'fetch-storage-quota',
    HANDLE_FETCH_STORAGE_QUOTA: 'handle-fetch-storage-quota',
    DOWNLOAD_FILE_FROM_DRIVE: 'download-file-from-drive',
    HANDLE_DOWNLOAD_FILE_FROM_DRIVE: 'handle-download-file-from-drive',
    REFRESH_DATA: 'refresh-renderer-data',
};