env:
  es6: true
  node: true
  browser: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent: [2, 4]
  prefer-destructuring: 1
  consistent-return: 1
  no-console: 1
  max-len: 1
  no-restricted-syntax: 0
