connection:
  server: ''
  user: ''
  password: ''
  database: ''
  pool: {
    max: 10,
    min: 0,
    idleTimeoutMillis: 30000
  }
drive:
  clientEmail: ''
  privateKey: ''
backup:
  time: '16:00'
  location: ''
  copyLocation: ''
info:
  lastBackup: ''
  availableBackups: 0
  freeSpace: 0
